
-- BORRADO DE OBJETOS
DROP TABLE GASTO_COMUN CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE EDIFICIO CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP SEQUENCE seq_com;


-- CREACION DE OBJETOS
CREATE TABLE COMUNA
(id_comuna NUMBER(6) NOT NULL,
 nombre_comuna VARCHAR2(30) NOT NULL,
 CONSTRAINT PK_COMUNA PRIMARY KEY (id_comuna));

CREATE TABLE ADMINISTRADOR 
(numrun_adm NUMBER(10) NOT NULL, 
 dvrun_adm VARCHAR2(1) NOT NULL, 
 pnombre_adm VARCHAR2(50) NOT NULL, 
 snombre_adm VARCHAR2(50), 
 appaterno_adm VARCHAR2(50) NOT NULL, 
 apmaterno_adm VARCHAR2(50),
 foto_adm BLOB,
 CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (numrun_adm));

CREATE TABLE EDIFICIO
(id_edif NUMBER(5) NOT NULL ,
 nombre_edif VARCHAR2 (50) NOT NULL ,
 direccion_edif VARCHAR2(60) NOT NULL,
 numrun_adm NUMBER(10) NOT NULL,
 id_comuna NUMBER(6) NOT NULL,
 CONSTRAINT PK_EDIFICIO PRIMARY KEY (id_edif));

CREATE TABLE DEPARTAMENTO
(id_edif NUMBER(5) NOT NULL ,
 nro_depto NUMBER(5) NOT NULL,
 total_banos_depto NUMBER(2) NOT NULL,
 total_dormitorios_depto NUMBER(2) NOT NULL,
 total_balcones_depto NUMBER(2),
 metros_cuadrados_depto NUMBER(5,2) NOT NULL,
 porc_prorrateo_depto NUMBER (3,2) NOT NULL,
 CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (id_edif, nro_depto));

CREATE TABLE GASTO_COMUN
(anno_mes_pcgc NUMBER(6) NOT NULL ,
 id_edif NUMBER(5) NOT NULL,
 nro_depto NUMBER(5) NOT NULL,
 fecha_desde_gc DATE NOT NULL ,
 fecha_hasta_gc DATE NOT NULL ,
 prorrateado_gc NUMBER (10,2) NOT NULL ,
 fondo_reserva_gc NUMBER (10,2) NOT NULL,
 agua_individual_gc NUMBER (10,2) NOT NULL ,
 combustible_individual_gc NUMBER (10,2) NOT NULL ,
 lavanderia_gc NUMBER (10,2),
 evento_gc NUMBER (10,2),
 servicio_gc NUMBER (10,2),
 monto_atrasado_gc NUMBER (10,2) ,
 multa_gc NUMBER (10,2) ,
 monto_total_gc NUMBER (10,2) NOT NULL,
 fecha_pago_gc DATE NOT NULL,
 CONSTRAINT PK_GASTO_COMUN PRIMARY KEY (anno_mes_pcgc,id_edif, nro_depto));

CREATE SEQUENCE seq_com START WITH 10 INCREMENT BY 10;

ALTER TABLE EDIFICIO ADD CONSTRAINT FK_EDIFICIO_ADMINISTRADOR FOREIGN KEY(numrun_adm) REFERENCES ADMINISTRADOR(numrun_adm);
ALTER TABLE EDIFICIO ADD CONSTRAINT FK_EDIFICIO_COMUNA FOREIGN KEY(id_comuna) REFERENCES COMUNA(id_comuna);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT FK_DEPARTAMENTO_EDIFICIO FOREIGN KEY(id_edif) REFERENCES EDIFICIO(id_edif);
ALTER TABLE GASTO_COMUN ADD CONSTRAINT FK_GCOMUN_DEPARTAMENTO FOREIGN KEY(id_edif, nro_depto) REFERENCES DEPARTAMENTO (id_edif, nro_depto);


